[tox]
minversion = 3.8
envlist = py3
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
commands =
    molecule --version
    {posargs:molecule test -s podman_slim --destroy always}